name: wegoo
description: Social travel companion app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_secure_storage: ^9.2.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^14.3.0
  cached_network_image: ^3.4.1
  flutter_animate: ^4.5.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  country_picker: ^2.0.26
  table_calendar: ^3.1.2
  uuid: ^4.5.1
  equatable: ^2.0.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  pin_code_fields: ^8.0.1
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-VariableFont_wght.ttf
          weight: 100
        - asset: assets/fonts/PlusJakartaSans-VariableFont_wght.ttf
          weight: 200
        - asset: assets/fonts/PlusJakartaSans-VariableFont_wght.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-VariableFont_wght.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-VariableFont_wght.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-VariableFont_wght.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-VariableFont_wght.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-VariableFont_wght.ttf
          weight: 800
        - asset: assets/fonts/PlusJakartaSans-Italic-VariableFont_wght.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Italic-VariableFont_wght.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Italic-VariableFont_wght.ttf
          style: italic
          weight: 700
  assets:
    - assets/images/